# Generated by Django 5.1 on 2024-09-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('token', models.TextField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blockboard',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
