# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy gongbae editor backend

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: zip create 
        run: zip -r ./editor-back.zip ./
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECERET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
      - name: Upload to S3 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CICD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_SECERET_KEY }}
        run: |
          aws s3 cp --region us-west-2 ./editor-back.zip s3://deform-gongbae/editor-back.zip
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name deform-editor
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --file-exists-behavior OVERWRITE
          --deployment-group-name deform-editor
          --s3-location bucket=deform-gongbae,key=editor-back.zip,bundleType=zip
